# Generated by Django 5.1.6 on 2025-03-25 08:49

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, help_text='Recurrence rule (e.g. every Monday and Friday with a repeat until date)', null=True),
        ),
    ]
