# Generated by Django 5.1.6 on 2025-03-22 20:52

import django.db.models.deletion
import django.utils.timezone
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_attended_alter_lecture_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='canceled',
        ),
        migrations.AddField(
            model_name='attendance',
            name='occurrence_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when this lecture occurrence happened'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date until which this lecture recurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, help_text='Recurrence rule (e.g. every Monday and Friday)', null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when recurrence begins'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=False, help_text='True if student was in the geofence'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(help_text='End time for the lecture occurrence'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(help_text='Start time for the lecture occurrence'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture', 'occurrence_date')},
        ),
        migrations.CreateModel(
            name='CanceledOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_occurrences', to='attendance.lecture')),
            ],
            options={
                'unique_together': {('lecture', 'occurrence_date')},
            },
        ),
    ]
